<?php
declare(strict_types = 1);

/** @var \Core\Entity\User|null $user */
$user = $this->user;

?>

<h1 class="page-header"><?php echo $this->title; ?></h1>

<div class="row">

    <div class="col-sm-12">

        <form id="user-form" class="form-horizontal" method="post">

            <div class="col-sm-12">

                <input type="hidden" name="user_id" value="<?php echo $user ?! $user->getId() : null; ?>" />

                <div class="form-group<?php echo isset($this->errors['user_gender']) ? ' has-error' : ''; ?>">
                    <select class="form-control" name="user_gender">
                        <?php foreach (\Core\Entity\User::GENDER_MAP as $value => $view) : ?>
                            <option value="<?php echo $value; ?>" <?php echo $value === ($user ? $user->getGender() : null); ?>><?php echo $view; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <?php if (isset($this->errors['user_gender'])): ?>
                        <ul class="help-block"><li><?php echo $this->errors['user_gender']; ?></li></ul>
                    <?php endif; ?>
                </div>

                <div class="form-group<?php echo isset($this->errors['user_first_name']) ? ' has-error' : ''; ?>">
                    <input type="text" name="user_first_name" class="form-control" value="<?php echo $user ? $user->getFirstName() : null; ?>" placeholder="First Name" />
                    <?php if (isset($this->errors['user_first_name'])): ?>
                        <ul class="help-block"><li><?php echo $this->errors['user_first_name']; ?></li></ul>
                    <?php endif; ?>
                </div>

                <div class="form-group<?php echo isset($this->errors['user_last_name']) ? ' has-error' : ''; ?>">
                    <input type="text" name="user_last_name" class="form-control" value="<?php echo $user ? $user->getLastName() : null; ?>" placeholder="Last Name" />
                    <?php if (isset($this->errors['user_last_name'])): ?>
                        <ul class="help-block"><li><?php echo $this->errors['user_last_name']; ?></li></ul>
                    <?php endif; ?>
                </div>

                <div class="form-group<?php echo isset($this->errors['user_email']) ? ' has-error' : ''; ?>">
                    <input type="text" name="user_email" class="form-control" value="<?php echo $user ? $user->getEmail() : null; ?>" placeholder="Email Address" />
                    <?php if (isset($this->errors['user_email'])): ?>
                        <ul class="help-block"><li><?php echo $this->errors['user_email']; ?></li></ul>
                    <?php endif; ?>
                </div>

                <div class="form-group<?php echo isset($this->errors['user_password']) ? ' has-error' : ''; ?>">
                    <input type="password" name="user_password" class="form-control" value="" placeholder="Password" autocomplete="false" />
                    <?php if (isset($this->errors['user_password'])): ?>
                        <ul class="help-block"><li><?php echo $this->errors['user_password']; ?></li></ul>
                    <?php endif; ?>
                </div>

            </div>

            <div class="pull-right">
                <button type="submit" class="btn btn-lg btn-primary">Speichern</button>
            </div>

        </form>

    </div>

</div>
