<?php
declare(strict_types = 1);

/** @var \Exception|null $exception */
$exception = $this->exception;

?>

<h1>500 - Server Error</h1>

<div class="row">

    <div class="col-sm-12">

        <?php if ($exception !== null): ?>

            <b><?php echo get_class($exception); ?></b><br />
            with Message <b><?php echo $exception->getMessage(); ?></b><br />
            Stack trace: <br />
            <i><?php echo $exception->getTraceAsString(); ?></i><br />
            Thrown in "<b><?php echo $exception->getFile(); ?></b>" on line <b><?php echo $exception->getLine(); ?></b>

        <?php else: ?>

            Whoops, that was'nt on purpose. Please try again later!

        <?php endif; ?>

    </div>

</div>

