<?php
declare (strict_types = 1);
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>MVC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='Shortcut icon' href='/favicon.ico' type='image/x-icon' />

    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/custom.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script
    <script src="/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">

    <div class="container">

        <?php if ($this->isAuthorised) : ?>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">MVC</a>
            </div>

            <div class="collapse navbar-collapse">

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/users" role="button">
                            <i class="fa fa-refresh"> </i> User Management
                        </a>
                    </li>
                    <li>
                        <a href="/logout" role="button">
                            <i class="fa fa-refresh"> </i> Logout
                        </a>
                    </li>
                </ul>

            </div>

        <?php else: ?>

            <div class="collapse navbar-collapse">

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/login" role="button">
                            <i class="fa fa-refresh"> </i> Login
                        </a>
                    </li>
                </ul>

            </div>

        <?php endif; ?>
    </div>
</nav>

<div class="container main-container">

    <div class="row">

        <div class="col-sm-12">

            <?php echo $this->content; ?>

        </div>

    </div>

    <hr />

    <footer>
        &copy; <?php echo date('Y') ?> by Mvc. All rights reserved.
    </footer>
</div>
</body>
</html>
