
<div class="modal-dialog">

    <div class="modal-content">

        <form id="login-form" method="post">

            <div class="modal-header">
                <h1 class="modal-title logo-font text-center"><?php echo $this->title; ?></h1>
            </div>
            <div class="modal-body">
                <?php if (count($this->errors) > 0): ?>
                    <div class="alert alert-danger" role="alert">
                        <?php echo implode('<br />', $this->errors); ?>
                    </div>
                <?php endif; ?>

                <input type="hidden" name="old-uri" value="" />

                <p>
                    <input type="text" name="username" class="form-control" value="<?php echo $this->username; ?>" placeholder="Email address" />
                </p>

                <p>
                    <input type="password" name="password" class="form-control" value="" placeholder="Password" autocomplete="false" />
                </p>

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-lg btn-block btn-primary">Login</button>
            </div>

        </form>

    </div>

</div>
